name: Staff
main: staff\Main
version: 1.0.0
api: [3.0.0, 3.0.0-ALHPA5, 3.0.0-ALHPA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12]
load: POSTWORLD
author: samangamerone
commands:
 staff:
  description: "Example2 command"
  usage: "samangamerone - ArshiaHacker - BardiaMiner - wolf_ali"